name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Image
        id: build-image
        uses: 8grams/github-buildpacks-action@v0.0.7
        with:
          app_name: "docker.io/8grams/parse-boilerplate"
          tag_name: "latest"
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Registry
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: "docker.io/8grams/parse-boilerplate"
          tags: "latest"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}